### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by mohamed-habib** [Ketabuk/Ketabuk-AndroidApp#1]
Hi @realkarim, i want to contribute at this project so can you please set a list of tasks to be added ?

**Comment by realkarim** [comment]
Hello Mohamed, the project follow the feature branch workflow, if you are not familiar with it you can check [this](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) tutorial.

I have only worked on the login and the register activities, you can check the website and implement any of the remaining activities like profile, user home, etc...

If you need to discuss in details we can do a Skype call, just send me your ID.

**Comment by mohamed-habib** [comment]
Thank you Karim, Here's my e-mail at Skype mohamed.mo.habib@gmail.com add me to your contacts and I'll reach you out if i need to discuss any thing.

**Comment by lordadamson** [comment]
I'd appreciate it if one of you would care to activate [this waffle board](https://waffle.io/Ketabuk/Ketabuk-AndroidApp) so that we can keep track of who's working and what and to lower the entry barriers for new comers and contributers.
Here are the waffle boards of the [webfront](https://waffle.io/Ketabuk/Ketabuk-Webfront) project and the [backend](https://waffle.io/Ketabuk/Ketabuk-Server) as examples.

**Comment by lordadamson** [comment]
@realkarim Can you please take the time to generate a few issues to help people contribute to the project? I'd really appreciate it because I don't really know what's going on in the project :D and I'd like to take advantage of the [hacktoberfest](https://hacktoberfest.digitalocean.com) of 2017
